server:
  port: 8083

app:
  name: social-ms
  version: 0.0.1-SNAPSHOT

spring:
  output:
    ansi:
      enabled: always
  application:
    name: social-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/social_db
    username: social_user
    password: social_pass
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: cl.worellana.social_ms.controller
