services:
  frontend:
    build:
      context: ./IronFeed-Frontend
    container_name: ironfeed-frontend-ssr
    environment:
      PORT: 4000
      NODE_ENV: production
    expose:
      - "4000"
    restart: unless-stopped

  nginx:
    image: nginx:1.29-alpine
    container_name: ironfeed-nginx
    environment:
      API_GATEWAY_UPSTREAM: ${API_GATEWAY_UPSTREAM}
      NGINX_ENVSUBST_FILTER: ^API_GATEWAY_UPSTREAM$
    ports:
      - "80:80"
    volumes:
      - ./deploy/public/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - frontend
    restart: unless-stopped
