services:
  frontend:
    build:
      context: ./IronFeed-Frontend
    container_name: ironfeed-frontend-ssr
    environment:
      PORT: 4000
      NODE_ENV: production
    expose:
      - "4000"
    restart: unless-stopped

  nginx:
    image: nginx:1.29-alpine
    container_name: ironfeed-nginx
    ports:
      - "80:80"
    volumes:
      - ./deploy/public/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    restart: unless-stopped
