server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: users-ms-auth
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**

            - id: users-ms
              uri: http://localhost:8081
              predicates:
                - Path=/api/users/**

            - id: workout-ms-routines
              uri: http://localhost:8082
              predicates:
                - Path=/api/routines/**

            - id: workout-ms-sessions
              uri: http://localhost:8082
              predicates:
                - Path=/api/workout-sessions/**

            - id: workout-ms-exercises
              uri: http://localhost:8082
              predicates:
                - Path=/api/exercises/**

            - id: workout-ms-personal-records
              uri: http://localhost:8082
              predicates:
                - Path=/api/personal-records/**

            - id: social-ms-follows
              uri: http://localhost:8083
              predicates:
                - Path=/api/follows/**

            - id: posts-ms
              uri: http://localhost:8084
              predicates:
                - Path=/api/posts/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  jwt:
    issuer: users-ms
    secret: ${JWT_SECRET}
