server:
  port: 8081

app:
  name: users-ms
  version: 0.0.1-SNAPSHOT

spring:
  output:
    ansi:
      enabled: always
  application:
    name: users-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: users_user
    password: users_pass
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    issuer: users-ms
    secret: ${JWT_SECRET}
    expiration-minutes: 60

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: cl.worellana.users_ms.controller
